# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  title: Personal site
  contentDir: content/en
  # weight: 1
# Uncomment the lines below to configure your website in a second language.
vn:
  languageCode: vn
  contentDir: content/vn
  title: Trang ca nhan
  # weight: 2
  params:
    description: Site description in VietNamese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
